
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_0_DEVICE_ID,
		XPAR_AXI_GPIO_0_BASEADDR,
		XPAR_AXI_GPIO_0_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_0_IS_DUAL
	},
	{
		XPAR_CS_N1_DEVICE_ID,
		XPAR_CS_N1_BASEADDR,
		XPAR_CS_N1_INTERRUPT_PRESENT,
		XPAR_CS_N1_IS_DUAL
	},
	{
		XPAR_SPI_MUX_SELECT_2_DEVICE_ID,
		XPAR_SPI_MUX_SELECT_2_BASEADDR,
		XPAR_SPI_MUX_SELECT_2_INTERRUPT_PRESENT,
		XPAR_SPI_MUX_SELECT_2_IS_DUAL
	},
	{
		XPAR_AXIS_ENABLE_DEVICE_ID,
		XPAR_AXIS_ENABLE_BASEADDR,
		XPAR_AXIS_ENABLE_INTERRUPT_PRESENT,
		XPAR_AXIS_ENABLE_IS_DUAL
	}
};


