@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 15 14:22:44 +0200 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_spi_master_behav -key {Behavioral:sim_2:Functional:tb_spi_master} -tclbatch tb_spi_master.tcl -protoinst "protoinst_files/spi_fifo_axis_module.protoinst" -view C:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_axis/spi_to_axis.tmp/spi_to_axi/tb_spi_master_behav.wcfg -log simulate.log"
call xsim  tb_spi_master_behav -key {Behavioral:sim_2:Functional:tb_spi_master} -tclbatch tb_spi_master.tcl -protoinst "protoinst_files/spi_fifo_axis_module.protoinst" -view C:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_axis/spi_to_axis.tmp/spi_to_axi/tb_spi_master_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
