# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.srcs/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0.xci
# IP: The module: 'clockwizard_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.srcs/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0.xci
# IP: The module: 'clockwizard_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwizard_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
