# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/clockwizard/clockwizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clockwizard || ORIG_REF_NAME==clockwizard} -quiet] -quiet

# IP: bd/clockwizard/ip/clockwizard_clk_wiz_0_0/clockwizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clockwizard_clk_wiz_0_0 || ORIG_REF_NAME==clockwizard_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/clocktest/clocktest.gen/sources_1/bd/clockwizard/clockwizard_ooc.xdc
