# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.srcs/sources_1/bd/histo/ip/histo_ila_sorter_0/histo_ila_sorter_0.xci
# IP: The module: 'histo_ila_sorter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/ip/histo_ila_sorter_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'histo_ila_sorter_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/ip/histo_ila_sorter_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'histo_ila_sorter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/ip/histo_ila_sorter_0/histo_ila_sorter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'histo_ila_sorter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.srcs/sources_1/bd/histo/ip/histo_ila_sorter_0/histo_ila_sorter_0.xci
# IP: The module: 'histo_ila_sorter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/ip/histo_ila_sorter_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'histo_ila_sorter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/ip/histo_ila_sorter_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'histo_ila_sorter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/ip/histo_ila_sorter_0/histo_ila_sorter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'histo_ila_sorter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
