# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# XDC: new/timing.xdc

# Block Designs: bd/signal_generator/signal_generator.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator || ORIG_REF_NAME==signal_generator} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/signal_generator_LVDS_to_AXIS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_LVDS_to_AXIS_0_0 || ORIG_REF_NAME==signal_generator_LVDS_to_AXIS_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_processing_system7_0_0/signal_generator_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_processing_system7_0_0 || ORIG_REF_NAME==signal_generator_processing_system7_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_rst_ps7_0_100M_0/signal_generator_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_rst_ps7_0_100M_0 || ORIG_REF_NAME==signal_generator_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_gpio_0_1/signal_generator_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_gpio_0_1 || ORIG_REF_NAME==signal_generator_axi_gpio_0_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlslice_0_0/signal_generator_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlslice_0_0 || ORIG_REF_NAME==signal_generator_xlslice_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlslice_1_0/signal_generator_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlslice_1_0 || ORIG_REF_NAME==signal_generator_xlslice_1_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlslice_1_1/signal_generator_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlslice_1_1 || ORIG_REF_NAME==signal_generator_xlslice_1_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlslice_1_2/signal_generator_xlslice_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlslice_1_2 || ORIG_REF_NAME==signal_generator_xlslice_1_2} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_quad_spi_0_0/signal_generator_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_quad_spi_0_0 || ORIG_REF_NAME==signal_generator_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_histo_0_0/signal_generator_histo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_histo_0_0 || ORIG_REF_NAME==signal_generator_histo_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_dma_0_0/signal_generator_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_dma_0_0 || ORIG_REF_NAME==signal_generator_axi_dma_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_mem_intercon_1/signal_generator_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_mem_intercon_1 || ORIG_REF_NAME==signal_generator_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_ila_0_2/signal_generator_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_ila_0_2 || ORIG_REF_NAME==signal_generator_ila_0_2} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_LD_LVDS_0/signal_generator_LD_LVDS_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_LD_LVDS_0 || ORIG_REF_NAME==signal_generator_LD_LVDS_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_PULSES_PER_PIXEL_0/signal_generator_PULSES_PER_PIXEL_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_PULSES_PER_PIXEL_0 || ORIG_REF_NAME==signal_generator_PULSES_PER_PIXEL_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_PULSES_PER_PIXEL_1/signal_generator_PULSES_PER_PIXEL_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_PULSES_PER_PIXEL_1 || ORIG_REF_NAME==signal_generator_PULSES_PER_PIXEL_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_gpio_0_2/signal_generator_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_gpio_0_2 || ORIG_REF_NAME==signal_generator_axi_gpio_0_2} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlconcat_0_0/signal_generator_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlconcat_0_0 || ORIG_REF_NAME==signal_generator_xlconcat_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_STOPRESULT_BITS_1/signal_generator_STOPRESULT_BITS_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_STOPRESULT_BITS_1 || ORIG_REF_NAME==signal_generator_STOPRESULT_BITS_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlconcat_1_0/signal_generator_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlconcat_1_0 || ORIG_REF_NAME==signal_generator_xlconcat_1_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_TLAST_COUNT_0/signal_generator_TLAST_COUNT_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_TLAST_COUNT_0 || ORIG_REF_NAME==signal_generator_TLAST_COUNT_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_REFINDEX_BITS_0/signal_generator_REFINDEX_BITS_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_REFINDEX_BITS_0 || ORIG_REF_NAME==signal_generator_REFINDEX_BITS_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_IMAGE_SIZE_0/signal_generator_IMAGE_SIZE_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_IMAGE_SIZE_0 || ORIG_REF_NAME==signal_generator_IMAGE_SIZE_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_laser_0_0/signal_generator_laser_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_laser_0_0 || ORIG_REF_NAME==signal_generator_laser_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_util_vector_logic_0_0/signal_generator_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_util_vector_logic_0_0 || ORIG_REF_NAME==signal_generator_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_util_idelay_ctrl_0_0/signal_generator_util_idelay_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_util_idelay_ctrl_0_0 || ORIG_REF_NAME==signal_generator_util_idelay_ctrl_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_smc_1/signal_generator_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_smc_1 || ORIG_REF_NAME==signal_generator_axi_smc_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_ila_0_5/signal_generator_ila_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_ila_0_5 || ORIG_REF_NAME==signal_generator_ila_0_5} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_ila_0_6/signal_generator_ila_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_ila_0_6 || ORIG_REF_NAME==signal_generator_ila_0_6} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_gpio_1_0 || ORIG_REF_NAME==signal_generator_axi_gpio_1_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_gpio_1_1/signal_generator_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_gpio_1_1 || ORIG_REF_NAME==signal_generator_axi_gpio_1_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_BINS_TO_READ_0/signal_generator_BINS_TO_READ_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_BINS_TO_READ_0 || ORIG_REF_NAME==signal_generator_BINS_TO_READ_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_xlconstant_0_4/signal_generator_xlconstant_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_xlconstant_0_4 || ORIG_REF_NAME==signal_generator_xlconstant_0_4} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_blk_mem_gen_0_0/signal_generator_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_blk_mem_gen_0_0 || ORIG_REF_NAME==signal_generator_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_bram_ctrl_0_1/signal_generator_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_bram_ctrl_0_1 || ORIG_REF_NAME==signal_generator_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_bram_ctrl_0_0/signal_generator_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_bram_ctrl_0_0 || ORIG_REF_NAME==signal_generator_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_ila_0_7/signal_generator_ila_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_ila_0_7 || ORIG_REF_NAME==signal_generator_ila_0_7} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_ila_0_8/signal_generator_ila_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_ila_0_8 || ORIG_REF_NAME==signal_generator_ila_0_8} -quiet] -quiet

# IP: bd/signal_generator/ip/signal_generator_axi_mem_intercon_imp_auto_pc_0/signal_generator_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signal_generator_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==signal_generator_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/signal_generator_ooc.xdc
