# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.runs/synth_1/signal_generator_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param bd.open.in_stealth_mode 1
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.cache/wt [current_project]
set_property parent.project_path C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/marce/AppData/Roaming/Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/IP/DDR_Fabric_2_always_debug
  c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/IP/barrel_histo
  c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/IP/DDR_Fabric
  c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/IP/DDR_LVDS_Fabric_IP
  c:/Users/marce/OneDrive/Dokumente/zynq_project/ip/laser_emulator
  c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/IP/histo_stream
  c:/Users/marce/OneDrive/Dokumente/zynq_project/ip/laser_emulator_xxl
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/hdl/signal_generator_wrapper.v
add_files C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/signal_generator.bd
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4_board.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/LVDS_to_AXIS_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_processing_system7_0_0/signal_generator_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_rst_ps7_0_100M_0/signal_generator_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_rst_ps7_0_100M_0/signal_generator_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_rst_ps7_0_100M_0/signal_generator_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_0_1/signal_generator_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_0_1/signal_generator_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_0_1/signal_generator_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_quad_spi_0_0/signal_generator_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_quad_spi_0_0/signal_generator_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_quad_spi_0_0/signal_generator_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_quad_spi_0_0/signal_generator_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/histo_ila_sorter_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_dma_0_0/signal_generator_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_dma_0_0/signal_generator_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_dma_0_0/signal_generator_axi_dma_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_2/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_2/signal_generator_ila_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_0_2/signal_generator_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_0_2/signal_generator_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_0_2/signal_generator_axi_gpio_0_2.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/laser_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_blk_mem_gen_0_2/laser_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_util_idelay_ctrl_0_0/signal_generator_util_idelay_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_1/bd_69d6_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_1/bd_69d6_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_2/bd_69d6_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_3/bd_69d6_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_4/bd_69d6_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_5/bd_69d6_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_6/bd_69d6_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_10/bd_69d6_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_11/bd_69d6_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_12/bd_69d6_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_13/bd_69d6_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_14/bd_69d6_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_15/bd_69d6_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_16/bd_69d6_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_17/bd_69d6_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_18/bd_69d6_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_19/bd_69d6_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_20/bd_69d6_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_21/bd_69d6_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_23/bd_69d6_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_24/bd_69d6_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_25/bd_69d6_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_26/bd_69d6_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_27/bd_69d6_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_28/bd_69d6_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_30/bd_69d6_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_31/bd_69d6_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_32/bd_69d6_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_33/bd_69d6_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_34/bd_69d6_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_35/bd_69d6_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_37/bd_69d6_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_38/bd_69d6_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_39/bd_69d6_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_40/bd_69d6_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_41/bd_69d6_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_42/bd_69d6_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_44/bd_69d6_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_45/bd_69d6_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_46/bd_69d6_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_47/bd_69d6_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_48/bd_69d6_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_49/bd_69d6_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_51/bd_69d6_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_52/bd_69d6_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_53/bd_69d6_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_54/bd_69d6_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_55/bd_69d6_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_56/bd_69d6_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_58/bd_69d6_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_59/bd_69d6_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_60/bd_69d6_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_61/bd_69d6_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_62/bd_69d6_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_63/bd_69d6_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_65/bd_69d6_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_66/bd_69d6_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_67/bd_69d6_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_68/bd_69d6_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_69/bd_69d6_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/bd_0/ip/ip_70/bd_69d6_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_smc_1/smartconnect.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_5/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_5/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_5/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_5/signal_generator_ila_0_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_6/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_6/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_6/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_6/signal_generator_ila_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_1/signal_generator_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_1/signal_generator_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_1/signal_generator_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_blk_mem_gen_0_0/signal_generator_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_bram_ctrl_0_1/signal_generator_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_bram_ctrl_0_0/signal_generator_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_7/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_7/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_7/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_7/signal_generator_ila_0_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_8/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_8/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_8/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_ila_0_8/signal_generator_ila_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_mem_intercon_imp_auto_pc_0/signal_generator_axi_mem_intercon_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/signal_generator_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/constrs_1/new/constraints.xdc]

read_xdc C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/utils_1/imports/synth_1/laser_signal_generator.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top signal_generator_wrapper -part xc7z020clg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef signal_generator_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file signal_generator_wrapper_utilization_synth.rpt -pb signal_generator_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
