# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LED_wrapper_0_1/TEST_PATTERN_TO_AXIS_LED_wrapper_0_1.xci
# IP: The module: 'TEST_PATTERN_TO_AXIS_LED_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/LED/LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED || ORIG_REF_NAME==LED} -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/LED/ip/LED_c_counter_binary_0_0/LED_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_c_counter_binary_0_0 || ORIG_REF_NAME==LED_c_counter_binary_0_0} -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/LED/ip/LED_xlslice_0_0/LED_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_xlslice_0_0 || ORIG_REF_NAME==LED_xlslice_0_0} -quiet] -quiet

# XDC: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/LED/LED_ooc.xdc

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LED_wrapper_0_1/TEST_PATTERN_TO_AXIS_LED_wrapper_0_1.xci
# IP: The module: 'TEST_PATTERN_TO_AXIS_LED_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/LED/LED.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED || ORIG_REF_NAME==LED} -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/LED/ip/LED_c_counter_binary_0_0/LED_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_c_counter_binary_0_0 || ORIG_REF_NAME==LED_c_counter_binary_0_0} -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.srcs/sources_1/bd/LED/ip/LED_xlslice_0_0/LED_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_xlslice_0_0 || ORIG_REF_NAME==LED_xlslice_0_0} -quiet] -quiet

# XDC: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/LED/LED_ooc.xdc
