# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/gpx2_dummy/gpx2_dummy.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_0/microzed_axi_dma_processing_system7_0_0.xci
# IP: The module: 'microzed_axi_dma_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/gpx2_dummy/gpx2_dummy.gen/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_0/microzed_axi_dma_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microzed_axi_dma_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/gpx2_dummy/gpx2_dummy.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_0/microzed_axi_dma_processing_system7_0_0.xci
# IP: The module: 'microzed_axi_dma_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/gpx2_dummy/gpx2_dummy.gen/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_0/microzed_axi_dma_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microzed_axi_dma_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
