# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/spi_fifo_axis_module/spi_fifo_axis_module.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_fifo_axis_module || ORIG_REF_NAME==spi_fifo_axis_module} -quiet] -quiet

# IP: bd/spi_fifo_axis_module/ip/spi_fifo_axis_module_fifo_generator_0_0/spi_fifo_axis_module_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_fifo_axis_module_fifo_generator_0_0 || ORIG_REF_NAME==spi_fifo_axis_module_fifo_generator_0_0} -quiet] -quiet

# IP: bd/spi_fifo_axis_module/ip/spi_fifo_axis_module_reset_not_gate_0/spi_fifo_axis_module_reset_not_gate_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_fifo_axis_module_reset_not_gate_0 || ORIG_REF_NAME==spi_fifo_axis_module_reset_not_gate_0} -quiet] -quiet

# IP: bd/spi_fifo_axis_module/ip/spi_fifo_axis_module_axi_stream_master_0_0/spi_fifo_axis_module_axi_stream_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_fifo_axis_module_axi_stream_master_0_0 || ORIG_REF_NAME==spi_fifo_axis_module_axi_stream_master_0_0} -quiet] -quiet

# IP: bd/spi_fifo_axis_module/ip/spi_fifo_axis_module_spi_master_1_0/spi_fifo_axis_module_spi_master_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_fifo_axis_module_spi_master_1_0 || ORIG_REF_NAME==spi_fifo_axis_module_spi_master_1_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_axis_development/spi_to_axis_development.gen/sources_1/bd/spi_fifo_axis_module/spi_fifo_axis_module_ooc.xdc
