# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_dma/spi_to_dma.srcs/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0/spi_to_dma_processing_system7_0_0.xci
# IP: The module: 'spi_to_dma_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_dma/spi_to_dma.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0/spi_to_dma_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_to_dma_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_dma/spi_to_dma.srcs/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0/spi_to_dma_processing_system7_0_0.xci
# IP: The module: 'spi_to_dma_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_dma/spi_to_dma.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0/spi_to_dma_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_to_dma_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
