# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.srcs/sources_1/bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1.xci
# IP: The module: 'LVDS_to_AXIS_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.gen/sources_1/bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LVDS_to_AXIS_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.gen/sources_1/bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'LVDS_to_AXIS_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.srcs/sources_1/bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1.xci
# IP: The module: 'LVDS_to_AXIS_util_ds_buf_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.gen/sources_1/bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LVDS_to_AXIS_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.gen/sources_1/bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'LVDS_to_AXIS_util_ds_buf_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
