transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/axis_infrastructure_v1_1_1
vlib riviera/axis_data_fifo_v2_0_15
vlib riviera/xil_defaultlib
vlib riviera/lib_pkg_v1_0_4
vlib riviera/fifo_generator_v13_2_11
vlib riviera/lib_fifo_v1_0_20
vlib riviera/lib_srl_fifo_v1_0_4
vlib riviera/lib_cdc_v1_0_3
vlib riviera/axi_datamover_v5_1_35
vlib riviera/axi_sg_v4_1_19
vlib riviera/axi_dma_v7_1_34
vlib riviera/xlconstant_v1_1_9
vlib riviera/dist_mem_gen_v8_0_15
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/interrupt_control_v3_1_5
vlib riviera/axi_quad_spi_v3_2_32
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_19
vlib riviera/processing_system7_vip_v1_0_21
vlib riviera/proc_sys_reset_v5_0_16
vlib riviera/smartconnect_v1_0
vlib riviera/axi_register_slice_v2_1_33
vlib riviera/axi_gpio_v2_0_35
vlib riviera/axi_bram_ctrl_v4_1_11
vlib riviera/blk_mem_gen_v8_4_9
vlib riviera/xlslice_v1_0_4
vlib riviera/generic_baseblocks_v2_1_2
vlib riviera/axi_data_fifo_v2_1_32
vlib riviera/axi_protocol_converter_v2_1_33

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap axis_infrastructure_v1_1_1 riviera/axis_infrastructure_v1_1_1
vmap axis_data_fifo_v2_0_15 riviera/axis_data_fifo_v2_0_15
vmap xil_defaultlib riviera/xil_defaultlib
vmap lib_pkg_v1_0_4 riviera/lib_pkg_v1_0_4
vmap fifo_generator_v13_2_11 riviera/fifo_generator_v13_2_11
vmap lib_fifo_v1_0_20 riviera/lib_fifo_v1_0_20
vmap lib_srl_fifo_v1_0_4 riviera/lib_srl_fifo_v1_0_4
vmap lib_cdc_v1_0_3 riviera/lib_cdc_v1_0_3
vmap axi_datamover_v5_1_35 riviera/axi_datamover_v5_1_35
vmap axi_sg_v4_1_19 riviera/axi_sg_v4_1_19
vmap axi_dma_v7_1_34 riviera/axi_dma_v7_1_34
vmap xlconstant_v1_1_9 riviera/xlconstant_v1_1_9
vmap dist_mem_gen_v8_0_15 riviera/dist_mem_gen_v8_0_15
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap interrupt_control_v3_1_5 riviera/interrupt_control_v3_1_5
vmap axi_quad_spi_v3_2_32 riviera/axi_quad_spi_v3_2_32
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_19 riviera/axi_vip_v1_1_19
vmap processing_system7_vip_v1_0_21 riviera/processing_system7_vip_v1_0_21
vmap proc_sys_reset_v5_0_16 riviera/proc_sys_reset_v5_0_16
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_register_slice_v2_1_33 riviera/axi_register_slice_v2_1_33
vmap axi_gpio_v2_0_35 riviera/axi_gpio_v2_0_35
vmap axi_bram_ctrl_v4_1_11 riviera/axi_bram_ctrl_v4_1_11
vmap blk_mem_gen_v8_4_9 riviera/blk_mem_gen_v8_4_9
vmap xlslice_v1_0_4 riviera/xlslice_v1_0_4
vmap generic_baseblocks_v2_1_2 riviera/generic_baseblocks_v2_1_2
vmap axi_data_fifo_v2_1_32 riviera/axi_data_fifo_v2_1_32
vmap axi_protocol_converter_v2_1_33 riviera/axi_protocol_converter_v2_1_33

vlog -work xilinx_vip  -incr "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axis_infrastructure_v1_1_1  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_15  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/sim/LVDS_to_AXIS_axis_data_fifo_0_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_0/util_ds_buf.vhd" \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_0/sim/LVDS_to_AXIS_util_ds_buf_0_0.vhd" \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/sim/LVDS_to_AXIS_util_ds_buf_0_1.vhd" \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/sim/LVDS_to_AXIS_util_ds_buf_1_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/sim/LVDS_to_AXIS_ila_0_0.v" \
"../../../bd/design_1/ipshared/d109/src/lvds_output.v" \
"../../../bd/design_1/ipshared/d109/sim/LVDS_to_AXIS_lvds_output_0_0.v" \
"../../../bd/design_1/ipshared/d109/src/DDR_fabric.v" \
"../../../bd/design_1/ipshared/d109/sim/LVDS_to_AXIS_DDR_fabric_0_0.v" \
"../../../bd/design_1/ipshared/d109/sim/LVDS_to_AXIS.v" \
"../../../bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/sim/design_1_LVDS_to_AXIS_0_0.v" \

vcom -work lib_pkg_v1_0_4 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_11  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/6080/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_11 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/6080/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_11  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/6080/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_20 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/e160/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_3 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_35 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/4277/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_19 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/fc5d/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_34 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/70ff/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_dma_0_0/sim/design_1_axi_dma_0_0.vhd" \

vlog -work xlconstant_v1_1_9  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \

vlog -work dist_mem_gen_v8_0_15  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/fa7e/simulation/dist_mem_gen_v8_0.v" \

vcom -work axi_lite_ipif_v3_0_4 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work interrupt_control_v3_1_5 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_quad_spi_v3_2_32 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/7d5e/hdl/axi_quad_spi_v3_2_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_quad_spi_0_0/sim/design_1_axi_quad_spi_0_0.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_19  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_21  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/sim/bd_afc3.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_0/sim/bd_afc3_one_0.v" \

vcom -work proc_sys_reset_v5_0_16 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/sim/bd_afc3_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/sim/bd_afc3_arsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/sim/bd_afc3_rsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/sim/bd_afc3_awsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/sim/bd_afc3_wsw_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/sim/bd_afc3_bsw_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/sim/bd_afc3_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/sim/bd_afc3_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/sim/bd_afc3_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/sim/bd_afc3_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/sim/bd_afc3_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/sim/bd_afc3_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/sim/bd_afc3_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/sim/bd_afc3_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/sim/bd_afc3_sbn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/sim/bd_afc3_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/sim/bd_afc3_m00arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/sim/bd_afc3_m00rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/sim/bd_afc3_m00awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/sim/bd_afc3_m00wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/sim/bd_afc3_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/sim/bd_afc3_m00e_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/sim/bd_afc3_m01s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/sim/bd_afc3_m01arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/sim/bd_afc3_m01rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/sim/bd_afc3_m01awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/sim/bd_afc3_m01wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/sim/bd_afc3_m01bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/sim/bd_afc3_m01e_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/sim/bd_afc3_m02s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/sim/bd_afc3_m02arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/sim/bd_afc3_m02rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/sim/bd_afc3_m02awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/sim/bd_afc3_m02wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/sim/bd_afc3_m02bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/sim/bd_afc3_m02e_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/sim/bd_afc3_m03s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/sim/bd_afc3_m03arn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/sim/bd_afc3_m03rn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_40/sim/bd_afc3_m03awn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_41/sim/bd_afc3_m03wn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/sim/bd_afc3_m03bn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/sim/bd_afc3_m03e_0.sv" \

vlog -work axi_register_slice_v2_1_33  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_smc_0/sim/design_1_axi_smc_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \

vcom -work axi_gpio_v2_0_35 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/6718/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \

vcom -work axi_bram_ctrl_v4_1_11 -93  -incr \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/df79/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
"../../../bd/design_1/ip/design_1_axi_bram_ctrl_1_0/sim/design_1_axi_bram_ctrl_1_0.vhd" \

vlog -work blk_mem_gen_v8_4_9  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \

vlog -work xlslice_v1_0_4  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/a97c/hdl/xlslice_v1_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
"../../../bd/design_1/ip/design_1_xlslice_0_1/sim/design_1_xlslice_0_1.v" \
"../../../bd/design_1/ip/design_1_xlslice_0_2/sim/design_1_xlslice_0_2.v" \
"../../../bd/design_1/ip/design_1_xlslice_0_3/sim/design_1_xlslice_0_3.v" \
"../../../bd/design_1/ip/design_1_xlslice_0_4/sim/design_1_xlslice_0_4.v" \
"../../../bd/design_1/ip/design_1_ila_1_0/sim/design_1_ila_1_0.v" \
"../../../bd/design_1/ip/design_1_ila_0_1/sim/design_1_ila_0_1.v" \
"../../../bd/design_1/ip/design_1_ila_0_2/sim/design_1_ila_0_2.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work generic_baseblocks_v2_1_2  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_32  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/65ce/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_33  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/27ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/86fe/hdl" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/0127/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ip/design_1_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/814a/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/1017/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/52c0/hdl/verilog" "+incdir+../../../../DDR_FABRIC_DMA_NEW.gen/sources_1/bd/design_1/ipshared/2276/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axis_infrastructure_v1_1_1 -l axis_data_fifo_v2_0_15 -l xil_defaultlib -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l dist_mem_gen_v8_0_15 -l axi_lite_ipif_v3_0_4 -l interrupt_control_v3_1_5 -l axi_quad_spi_v3_2_32 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l axi_gpio_v2_0_35 -l axi_bram_ctrl_v4_1_11 -l blk_mem_gen_v8_4_9 -l xlslice_v1_0_4 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_protocol_converter_v2_1_33 \
"../../../bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_0/sim/design_1_axi_mem_intercon_imp_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

