# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/LED/LED.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED || ORIG_REF_NAME==LED} -quiet] -quiet

# IP: bd/LED/ip/LED_c_counter_binary_0_0/LED_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_c_counter_binary_0_0 || ORIG_REF_NAME==LED_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/LED/ip/LED_xlslice_0_0/LED_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_xlslice_0_0 || ORIG_REF_NAME==LED_xlslice_0_0} -quiet] -quiet

# Block Designs: bd/TEST_PATTERN_TO_AXIS/TEST_PATTERN_TO_AXIS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_spi_top_0_0/TEST_PATTERN_TO_AXIS_spi_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_spi_top_0_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_spi_top_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_xlconstant_0_0/TEST_PATTERN_TO_AXIS_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_xlconstant_0_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_xlconstant_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_xlconstant_0_1/TEST_PATTERN_TO_AXIS_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_xlconstant_0_1 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_xlconstant_0_1} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LED_wrapper_0_0/TEST_PATTERN_TO_AXIS_LED_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_LED_wrapper_0_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_LED_wrapper_0_0} -quiet] -quiet

# Block Designs: bd/LED/LED.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED || ORIG_REF_NAME==LED} -quiet] -quiet

# IP: bd/LED/ip/LED_c_counter_binary_0_0/LED_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_c_counter_binary_0_0 || ORIG_REF_NAME==LED_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/LED/ip/LED_xlslice_0_0/LED_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_xlslice_0_0 || ORIG_REF_NAME==LED_xlslice_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LED_wrapper_0_1/TEST_PATTERN_TO_AXIS_LED_wrapper_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_LED_wrapper_0_1 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_LED_wrapper_0_1} -quiet] -quiet

# Block Designs: bd/LED/LED.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED || ORIG_REF_NAME==LED} -quiet] -quiet

# IP: bd/LED/ip/LED_c_counter_binary_0_0/LED_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_c_counter_binary_0_0 || ORIG_REF_NAME==LED_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/LED/ip/LED_xlslice_0_0/LED_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_xlslice_0_0 || ORIG_REF_NAME==LED_xlslice_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LED_wrapper_1_0/TEST_PATTERN_TO_AXIS_LED_wrapper_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_LED_wrapper_1_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_LED_wrapper_1_0} -quiet] -quiet

# Block Designs: bd/LED/LED.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED || ORIG_REF_NAME==LED} -quiet] -quiet

# IP: bd/LED/ip/LED_c_counter_binary_0_0/LED_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_c_counter_binary_0_0 || ORIG_REF_NAME==LED_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/LED/ip/LED_xlslice_0_0/LED_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LED_xlslice_0_0 || ORIG_REF_NAME==LED_xlslice_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_ila_0_0/TEST_PATTERN_TO_AXIS_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_ila_0_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_ila_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_ila_2_0/TEST_PATTERN_TO_AXIS_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_ila_2_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_ila_2_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_clk_wiz_0/TEST_PATTERN_TO_AXIS_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_clk_wiz_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_clk_wiz_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0} -quiet] -quiet

# IP: bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_clk_wiz_0_0/TEST_PATTERN_TO_AXIS_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_PATTERN_TO_AXIS_clk_wiz_0_0 || ORIG_REF_NAME==TEST_PATTERN_TO_AXIS_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/LED/LED_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/LED/LED_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/LED/LED_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/LED/LED_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/ONECHANNEL/ONECHANNEL.gen/sources_1/bd/TEST_PATTERN_TO_AXIS/TEST_PATTERN_TO_AXIS_ooc.xdc
