# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/signal_generator_laser_0_0.xci
# IP: The module: 'signal_generator_laser_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_bram_ctrl_laser_0 || ORIG_REF_NAME==laser_bram_ctrl_laser_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_bram_ctrl_sw_0/laser_bram_ctrl_sw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_bram_ctrl_sw_0 || ORIG_REF_NAME==laser_bram_ctrl_sw_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_blk_mem_gen_0_2/laser_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_blk_mem_gen_0_2 || ORIG_REF_NAME==laser_blk_mem_gen_0_2} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/laser_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_blk_mem_gen_0_2/laser_blk_mem_gen_0_2_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/laser_ila_0_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_psr_aclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_s00a2s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_sarn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_srn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_m00s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/signal_generator_laser_0_0.xci
# IP: The module: 'signal_generator_laser_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_bram_ctrl_laser_0 || ORIG_REF_NAME==laser_bram_ctrl_laser_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_bram_ctrl_sw_0/laser_bram_ctrl_sw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_bram_ctrl_sw_0 || ORIG_REF_NAME==laser_bram_ctrl_sw_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_blk_mem_gen_0_2/laser_blk_mem_gen_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_blk_mem_gen_0_2 || ORIG_REF_NAME==laser_blk_mem_gen_0_2} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/laser_ila_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_blk_mem_gen_0_2/laser_blk_mem_gen_0_2_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ila_0_1/laser_ila_0_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_psr_aclk_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_s00a2s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_sarn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_srn_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/bd_df2e_m00s2a_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_laser_0_0/src/laser_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_laser_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
