# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/spi_to_dma/spi_to_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma || ORIG_REF_NAME==spi_to_dma} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0_2/spi_to_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_processing_system7_0_0 || ORIG_REF_NAME==spi_to_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_dma_0_0_2/spi_to_dma_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_dma_0_0 || ORIG_REF_NAME==spi_to_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/spi_to_dma_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_smc_0 || ORIG_REF_NAME==spi_to_dma_axi_smc_0} -quiet] -quiet

# Block Designs: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/bd_2a6b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_0/bd_2a6b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_1/bd_2a6b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_2/bd_2a6b_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_3/bd_2a6b_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_4/bd_2a6b_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_5/bd_2a6b_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_6/bd_2a6b_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_7/bd_2a6b_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_8/bd_2a6b_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_9/bd_2a6b_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_10/bd_2a6b_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_11/bd_2a6b_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_12/bd_2a6b_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_13/bd_2a6b_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_14/bd_2a6b_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_15/bd_2a6b_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_16/bd_2a6b_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_17/bd_2a6b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_18/bd_2a6b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_19/bd_2a6b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_20/bd_2a6b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_21/bd_2a6b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_22/bd_2a6b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_23/bd_2a6b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_24/bd_2a6b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_25/bd_2a6b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_26/bd_2a6b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_27/bd_2a6b_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_28/bd_2a6b_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_29/bd_2a6b_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_30/bd_2a6b_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_31/bd_2a6b_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_32/bd_2a6b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_33/bd_2a6b_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_34/bd_2a6b_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_35/bd_2a6b_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_36/bd_2a6b_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_37/bd_2a6b_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_38/bd_2a6b_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_39/bd_2a6b_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_40/bd_2a6b_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_41/bd_2a6b_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_42/bd_2a6b_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_43/bd_2a6b_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_44/bd_2a6b_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_45/bd_2a6b_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_46/bd_2a6b_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/spi_to_dma/ip/spi_to_dma_rst_ps7_0_50M_0_2/spi_to_dma_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_rst_ps7_0_50M_0 || ORIG_REF_NAME==spi_to_dma_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_0_2/spi_to_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_mem_intercon_0 || ORIG_REF_NAME==spi_to_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/spi_to_dma_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_quad_spi_0_0 || ORIG_REF_NAME==spi_to_dma_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_gpio_0_2/spi_to_dma_axi_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_gpio_0 || ORIG_REF_NAME==spi_to_dma_axi_gpio_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_xlslice_0_0_2/spi_to_dma_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_xlslice_0_0 || ORIG_REF_NAME==spi_to_dma_xlslice_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_SPI_En_0_1/spi_to_dma_SPI_En_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_SPI_En_0 || ORIG_REF_NAME==spi_to_dma_SPI_En_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_dma_start_0_1/spi_to_dma_dma_start_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_dma_start_0 || ORIG_REF_NAME==spi_to_dma_dma_start_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_result_channel_0_1/spi_to_dma_result_channel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_result_channel_0 || ORIG_REF_NAME==spi_to_dma_result_channel_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_xlslice_1_0/spi_to_dma_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_xlslice_1_0 || ORIG_REF_NAME==spi_to_dma_xlslice_1_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_xlslice_1_1/spi_to_dma_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_xlslice_1_1 || ORIG_REF_NAME==spi_to_dma_xlslice_1_1} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_xlslice_2_0/spi_to_dma_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_xlslice_2_0 || ORIG_REF_NAME==spi_to_dma_xlslice_2_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_xlslice_1_2/spi_to_dma_xlslice_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_xlslice_1_2 || ORIG_REF_NAME==spi_to_dma_xlslice_1_2} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_ila_0_0/spi_to_dma_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_0 || ORIG_REF_NAME==spi_to_dma_ila_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_ila_LVDS_DMA_0/spi_to_dma_ila_LVDS_DMA_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_LVDS_DMA_0 || ORIG_REF_NAME==spi_to_dma_ila_LVDS_DMA_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/spi_to_dma_LVDS_to_AXIS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_LVDS_to_AXIS_0_0 || ORIG_REF_NAME==spi_to_dma_LVDS_to_AXIS_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_ila_0_1/spi_to_dma_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_1 || ORIG_REF_NAME==spi_to_dma_ila_0_1} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_clk_wiz_0_0/spi_to_dma_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_clk_wiz_0_0 || ORIG_REF_NAME==spi_to_dma_clk_wiz_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_ila_0_2/spi_to_dma_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_2 || ORIG_REF_NAME==spi_to_dma_ila_0_2} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_ila_0_3/spi_to_dma_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_3 || ORIG_REF_NAME==spi_to_dma_ila_0_3} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_imp_auto_pc_0/spi_to_dma_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==spi_to_dma_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0_2/spi_to_dma_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_processing_system7_0_0 || ORIG_REF_NAME==spi_to_dma_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_dma_0_0_2/spi_to_dma_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_dma_0_0 || ORIG_REF_NAME==spi_to_dma_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_dma_0_0_2/spi_to_dma_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_dma_0_0 || ORIG_REF_NAME==spi_to_dma_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_1/bd_2a6b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_1/bd_2a6b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_2/bd_2a6b_arinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_3/bd_2a6b_rinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_4/bd_2a6b_awinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_5/bd_2a6b_winsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_6/bd_2a6b_binsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_7/bd_2a6b_aroutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_8/bd_2a6b_routsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_9/bd_2a6b_awoutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_10/bd_2a6b_woutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_11/bd_2a6b_boutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_12/bd_2a6b_arni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_13/bd_2a6b_rni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_14/bd_2a6b_awni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_15/bd_2a6b_wni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_16/bd_2a6b_bni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_20/bd_2a6b_s00a2s_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_21/bd_2a6b_sarn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_22/bd_2a6b_srn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_23/bd_2a6b_sawn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_24/bd_2a6b_swn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_25/bd_2a6b_sbn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_26/bd_2a6b_m00s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_27/bd_2a6b_m00arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_28/bd_2a6b_m00rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_29/bd_2a6b_m00awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_30/bd_2a6b_m00wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_31/bd_2a6b_m00bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_33/bd_2a6b_m03s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_34/bd_2a6b_m03arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_35/bd_2a6b_m03rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_36/bd_2a6b_m03awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_37/bd_2a6b_m03wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_38/bd_2a6b_m03bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_40/bd_2a6b_m04s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_41/bd_2a6b_m04arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_42/bd_2a6b_m04rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_43/bd_2a6b_m04awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_44/bd_2a6b_m04wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_45/bd_2a6b_m04bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_smc_0 || ORIG_REF_NAME==spi_to_dma_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_rst_ps7_0_50M_0_2/spi_to_dma_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_rst_ps7_0_50M_0 || ORIG_REF_NAME==spi_to_dma_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_rst_ps7_0_50M_0_2/spi_to_dma_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_rst_ps7_0_50M_0 || ORIG_REF_NAME==spi_to_dma_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/spi_to_dma_axi_quad_spi_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_quad_spi_0_0 || ORIG_REF_NAME==spi_to_dma_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/spi_to_dma_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_quad_spi_0_0 || ORIG_REF_NAME==spi_to_dma_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/spi_to_dma_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/spi_to_dma_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_quad_spi_0_0 || ORIG_REF_NAME==spi_to_dma_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_gpio_0_2/spi_to_dma_axi_gpio_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_gpio_0 || ORIG_REF_NAME==spi_to_dma_axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_gpio_0_2/spi_to_dma_axi_gpio_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_gpio_0_2/spi_to_dma_axi_gpio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_gpio_0 || ORIG_REF_NAME==spi_to_dma_axi_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_0 || ORIG_REF_NAME==spi_to_dma_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_0 || ORIG_REF_NAME==spi_to_dma_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_0/spi_to_dma_ila_0_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_LVDS_DMA_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_LVDS_DMA_0 || ORIG_REF_NAME==spi_to_dma_ila_LVDS_DMA_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_LVDS_DMA_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_LVDS_DMA_0 || ORIG_REF_NAME==spi_to_dma_ila_LVDS_DMA_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_LVDS_DMA_0/spi_to_dma_ila_LVDS_DMA_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_1 || ORIG_REF_NAME==spi_to_dma_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_1 || ORIG_REF_NAME==spi_to_dma_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_1/spi_to_dma_ila_0_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_clk_wiz_0_0/spi_to_dma_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_clk_wiz_0_0 || ORIG_REF_NAME==spi_to_dma_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_clk_wiz_0_0/spi_to_dma_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_clk_wiz_0_0 || ORIG_REF_NAME==spi_to_dma_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_clk_wiz_0_0/spi_to_dma_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_2 || ORIG_REF_NAME==spi_to_dma_ila_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_2 || ORIG_REF_NAME==spi_to_dma_ila_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_2/spi_to_dma_ila_0_2_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_3 || ORIG_REF_NAME==spi_to_dma_ila_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_3/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==spi_to_dma_ila_0_3 || ORIG_REF_NAME==spi_to_dma_ila_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_3/spi_to_dma_ila_0_3_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_imp_auto_pc_0/spi_to_dma_axi_mem_intercon_imp_auto_pc_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/spi_to_dma_ooc.xdc
