# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lvds_constraints.xdc

# Block Designs: bd/led/led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led || ORIG_REF_NAME==led} -quiet] -quiet

# IP: bd/led/ip/led_c_counter_binary_0_0/led_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_c_counter_binary_0_0 || ORIG_REF_NAME==led_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/led/ip/led_xlslice_0_0/led_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_xlslice_0_0 || ORIG_REF_NAME==led_xlslice_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_sandbox/LVDS_sandbox.gen/sources_1/bd/led/led_ooc.xdc
