# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.runs/synth_1/.Xil/Vivado-10952-LAPTOP-UKM8GMC3/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/86fe/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/f0b6/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/0127/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/ec67/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/814a/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1017/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/52c0/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/2276/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/3cbc
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/netlist
  } {
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_2/synth/bd_2a6b_arinsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_3/synth/bd_2a6b_rinsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_4/synth/bd_2a6b_awinsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_5/synth/bd_2a6b_winsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_6/synth/bd_2a6b_binsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_7/synth/bd_2a6b_aroutsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_8/synth/bd_2a6b_routsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_9/synth/bd_2a6b_awoutsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_10/synth/bd_2a6b_woutsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_11/synth/bd_2a6b_boutsw_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_12/synth/bd_2a6b_arni_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_13/synth/bd_2a6b_rni_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_14/synth/bd_2a6b_awni_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_15/synth/bd_2a6b_wni_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_16/synth/bd_2a6b_bni_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_17/synth/bd_2a6b_s00mmu_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_18/synth/bd_2a6b_s00tr_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_19/synth/bd_2a6b_s00sic_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_20/synth/bd_2a6b_s00a2s_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_21/synth/bd_2a6b_sarn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_22/synth/bd_2a6b_srn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_23/synth/bd_2a6b_sawn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_24/synth/bd_2a6b_swn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_25/synth/bd_2a6b_sbn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_26/synth/bd_2a6b_m00s2a_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_27/synth/bd_2a6b_m00arn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_28/synth/bd_2a6b_m00rn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_29/synth/bd_2a6b_m00awn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_30/synth/bd_2a6b_m00wn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_31/synth/bd_2a6b_m00bn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_32/synth/bd_2a6b_m00e_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_33/synth/bd_2a6b_m03s2a_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_34/synth/bd_2a6b_m03arn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_35/synth/bd_2a6b_m03rn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_36/synth/bd_2a6b_m03awn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_37/synth/bd_2a6b_m03wn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_38/synth/bd_2a6b_m03bn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_39/synth/bd_2a6b_m03e_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_40/synth/bd_2a6b_m04s2a_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_41/synth/bd_2a6b_m04arn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_42/synth/bd_2a6b_m04rn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_43/synth/bd_2a6b_m04awn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_44/synth/bd_2a6b_m04wn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_45/synth/bd_2a6b_m04bn_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_46/synth/bd_2a6b_m04e_0.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/states.sv
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/lvds_receiver.sv
    }
      rt::read_verilog -include {
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/86fe/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/f0b6/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/0127/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/ec67/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/814a/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1017/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/52c0/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/2276/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/3cbc
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/netlist
  } {
      C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/hdl/spi_to_dma_wrapper.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/synth/spi_to_dma.v
    }
      rt::read_verilog -include {
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/86fe/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/f0b6/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/0127/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/ec67/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/814a/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1017/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/52c0/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/2276/hdl/verilog
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/3cbc
    c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/netlist
  } {
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0_2/hdl/verilog/processing_system7_v5_5_processing_system7.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0_2/synth/spi_to_dma_processing_system7_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_0/synth/bd_2a6b_one_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/synth/bd_2a6b.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/synth/spi_to_dma_axi_smc_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/65ce/hdl/axi_data_fifo_v2_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/27ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_imp_auto_pc_0/synth/spi_to_dma_axi_mem_intercon_imp_auto_pc_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a97c/hdl/xlslice_v1_0_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_xlslice_0_0_2/synth/spi_to_dma_xlslice_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_SPI_En_0_1/synth/spi_to_dma_SPI_En_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_dma_start_0_1/synth/spi_to_dma_dma_start_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_result_channel_0_1/synth/spi_to_dma_result_channel_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_xlslice_1_0/synth/spi_to_dma_xlslice_1_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_xlslice_1_1/synth/spi_to_dma_xlslice_1_1.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_xlslice_2_0/synth/spi_to_dma_xlslice_2_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_xlslice_1_2/synth/spi_to_dma_xlslice_1_2.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/814a/hdl/ltlib_v1_0_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1017/hdl/xsdbs_v1_0_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/52c0/hdl/xsdbm_v3_0_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/2276/hdl/ila_v6_2_syn_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_0/synth/spi_to_dma_ila_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_LVDS_DMA_0/synth/spi_to_dma_ila_LVDS_DMA_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl/axis_infrastructure_v1_1_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/hdl/axis_data_fifo_v2_0_vl_rfs.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/synth/LVDS_to_AXIS_axis_data_fifo_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/lvds_master.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/LVDS_to_AXIS_lvds_master_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/lvds_output.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/LVDS_to_AXIS_lvds_output_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/lvds_input.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/LVDS_to_AXIS_lvds_input_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/LVDS_to_AXIS_l_clk_in_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/LVDS_to_AXIS_sdo_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/a91b/src/LVDS_to_AXIS.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_LVDS_to_AXIS_0_0/synth/spi_to_dma_LVDS_to_AXIS_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_1/synth/spi_to_dma_ila_0_1.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_clk_wiz_0_0/spi_to_dma_clk_wiz_0_0_clk_wiz.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_clk_wiz_0_0/spi_to_dma_clk_wiz_0_0.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_2/synth/spi_to_dma_ila_0_2.v
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_ila_0_3/synth/spi_to_dma_ila_0_3.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_4 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_9 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/5ec1/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_11 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/6080/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_20 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/e160/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_4 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_3 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_35 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/4277/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_sg_v4_1_19 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/fc5d/hdl/axi_sg_v4_1_rfs.vhd
      rt::read_vhdl -lib axi_dma_v7_1_34 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/70ff/hdl/axi_dma_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_dma_0_0_2/synth/spi_to_dma_axi_dma_0_0.vhd
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_smc_0_2/bd_0/ip/ip_1/synth/bd_2a6b_psr_aclk_0.vhd
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_rst_ps7_0_50M_0_2/synth/spi_to_dma_rst_ps7_0_50M_0.vhd
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0_2/synth/spi_to_dma_axi_quad_spi_0_0.vhd
      c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ip/spi_to_dma_axi_gpio_0_2/synth/spi_to_dma_axi_gpio_0.vhd
    }
      rt::read_vhdl -lib proc_sys_reset_v5_0_16 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib dist_mem_gen_v8_0_15 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/fa7e/hdl/dist_mem_gen_v8_0_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib interrupt_control_v3_1_5 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_quad_spi_v3_2_32 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/7d5e/hdl/axi_quad_spi_v3_2_rfs.vhd
      rt::read_vhdl -lib axi_gpio_v2_0_35 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/6718/hdl/axi_gpio_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_3_7 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1a4e/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_5 c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.gen/sources_1/bd/spi_to_dma/ipshared/1665/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.runs/synth_1/.Xil/Vivado-10952-LAPTOP-UKM8GMC3/realtime/spi_to_dma_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top spi_to_dma_wrapper
    rt::set_parameter incrementalOnCache "C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.runs/synth_1/.Xil/Vivado-10952-LAPTOP-UKM8GMC3/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS2DMAc/LVDS2DMAc/LVDS2DMAc.runs/synth_1/.Xil/Vivado-10952-LAPTOP-UKM8GMC3/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
