# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/laser/laser.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser || ORIG_REF_NAME==laser} -quiet] -quiet

# IP: bd/laser/ip/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_bram_ctrl_laser_0 || ORIG_REF_NAME==laser_bram_ctrl_laser_0} -quiet] -quiet

# IP: bd/laser/ip/laser_bram_ctrl_sw_0/laser_bram_ctrl_sw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_bram_ctrl_sw_0 || ORIG_REF_NAME==laser_bram_ctrl_sw_0} -quiet] -quiet

# IP: bd/laser/ip/laser_laser_signal_generat_0_0/laser_laser_signal_generat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_laser_signal_generat_0_0 || ORIG_REF_NAME==laser_laser_signal_generat_0_0} -quiet] -quiet

# IP: bd/laser/ip/laser_blk_mem_gen_0_2/laser_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_blk_mem_gen_0_2 || ORIG_REF_NAME==laser_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/laser/ip/laser_ila_0_1/laser_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_ila_0_1 || ORIG_REF_NAME==laser_ila_0_1} -quiet] -quiet

# IP: bd/laser/ip/laser_axi_smc_0/laser_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==laser_axi_smc_0 || ORIG_REF_NAME==laser_axi_smc_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/emulator_4x8bit/emulator_4x8bit.gen/sources_1/bd/laser/laser_ooc.xdc
