# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/signal_generator_histo_0_0.xci
# IP: The module: 'signal_generator_histo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_axis_data_fifo_0_0/histo_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_axis_data_fifo_0_0 || ORIG_REF_NAME==histo_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_in_line_and_in_frame_0/histo_in_line_and_in_frame_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_in_line_and_in_frame_0 || ORIG_REF_NAME==histo_in_line_and_in_frame_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_util_vector_logic_0_0/histo_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_util_vector_logic_0_0 || ORIG_REF_NAME==histo_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_util_vector_logic_1_1/histo_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_util_vector_logic_1_1 || ORIG_REF_NAME==histo_util_vector_logic_1_1} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_xlconstant_0_0/histo_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_xlconstant_0_0 || ORIG_REF_NAME==histo_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/histo_ila_sorter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/histo_ila_sorter_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_histo_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/signal_generator_histo_0_0.xci
# IP: The module: 'signal_generator_histo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_axis_data_fifo_0_0/histo_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_axis_data_fifo_0_0 || ORIG_REF_NAME==histo_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_in_line_and_in_frame_0/histo_in_line_and_in_frame_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_in_line_and_in_frame_0 || ORIG_REF_NAME==histo_in_line_and_in_frame_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_util_vector_logic_0_0/histo_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_util_vector_logic_0_0 || ORIG_REF_NAME==histo_util_vector_logic_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_util_vector_logic_1_1/histo_util_vector_logic_1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_util_vector_logic_1_1 || ORIG_REF_NAME==histo_util_vector_logic_1_1} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_xlconstant_0_0/histo_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_xlconstant_0_0 || ORIG_REF_NAME==histo_xlconstant_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/histo_ila_sorter_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ila_sorter_0/histo_ila_sorter_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_histo_0_0/src/histo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_histo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
