# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/main_constraints.xdc

# Block Designs: bd/spi_to_dma/spi_to_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma || ORIG_REF_NAME==spi_to_dma} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_processing_system7_0_0/spi_to_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_processing_system7_0_0 || ORIG_REF_NAME==spi_to_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_dma_0_0/spi_to_dma_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_dma_0_0 || ORIG_REF_NAME==spi_to_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_smc_0/spi_to_dma_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_smc_0 || ORIG_REF_NAME==spi_to_dma_axi_smc_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_rst_ps7_0_50M_0/spi_to_dma_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_rst_ps7_0_50M_0 || ORIG_REF_NAME==spi_to_dma_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_0/spi_to_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_mem_intercon_0 || ORIG_REF_NAME==spi_to_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_spi_multiplexer_0_1/spi_to_dma_spi_multiplexer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_spi_multiplexer_0_1 || ORIG_REF_NAME==spi_to_dma_spi_multiplexer_0_1} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_gpio_0_0/spi_to_dma_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_gpio_0_0 || ORIG_REF_NAME==spi_to_dma_axi_gpio_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_spi_mux_select_0/spi_to_dma_spi_mux_select_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_spi_mux_select_0 || ORIG_REF_NAME==spi_to_dma_spi_mux_select_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_quad_spi_0_0/spi_to_dma_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_quad_spi_0_0 || ORIG_REF_NAME==spi_to_dma_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_spi_fifo_axis_module_0_0/spi_to_dma_spi_fifo_axis_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_spi_fifo_axis_module_0_0 || ORIG_REF_NAME==spi_to_dma_spi_fifo_axis_module_0_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_imp_auto_pc_0/spi_to_dma_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==spi_to_dma_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/spi_to_dma/ip/spi_to_dma_axi_mem_intercon_imp_auto_us_0/spi_to_dma_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_to_dma_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==spi_to_dma_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/spi_to_dma/spi_to_dma.gen/sources_1/bd/spi_to_dma/spi_to_dma_ooc.xdc
