# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microzed_axi_dma/microzed_axi_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma || ORIG_REF_NAME==microzed_axi_dma} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_0/microzed_axi_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_processing_system7_0_0 || ORIG_REF_NAME==microzed_axi_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_dma_0_0/microzed_axi_dma_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_dma_0_0 || ORIG_REF_NAME==microzed_axi_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_ps7_0_axi_periph_imp_xbar_0/microzed_axi_dma_ps7_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_ps7_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==microzed_axi_dma_ps7_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_ps7_0_axi_periph_0/microzed_axi_dma_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==microzed_axi_dma_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_rst_ps7_0_50M_0/microzed_axi_dma_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_rst_ps7_0_50M_0 || ORIG_REF_NAME==microzed_axi_dma_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_mem_intercon_0/microzed_axi_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_mem_intercon_0 || ORIG_REF_NAME==microzed_axi_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_sample_generator2_0_0/microzed_axi_dma_sample_generator2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_sample_generator2_0_0 || ORIG_REF_NAME==microzed_axi_dma_sample_generator2_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_gpio_0_0/microzed_axi_dma_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_gpio_0_0 || ORIG_REF_NAME==microzed_axi_dma_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_gpio_1_0/microzed_axi_dma_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_gpio_1_0 || ORIG_REF_NAME==microzed_axi_dma_axi_gpio_1_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_ps7_0_axi_periph_imp_auto_pc_0/microzed_axi_dma_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==microzed_axi_dma_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_mem_intercon_imp_auto_pc_0/microzed_axi_dma_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==microzed_axi_dma_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_mem_intercon_imp_auto_us_0/microzed_axi_dma_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==microzed_axi_dma_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/gpx2_dummy/gpx2_dummy.gen/sources_1/bd/microzed_axi_dma/microzed_axi_dma_ooc.xdc
