# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_TEST_PATTERN_READOUT/LVDS_TEST_PATTERN_READOUT.srcs/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0.xci
# IP: The module: 'TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_TEST_PATTERN_READOUT/LVDS_TEST_PATTERN_READOUT.gen/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_TEST_PATTERN_READOUT/LVDS_TEST_PATTERN_READOUT.gen/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_TEST_PATTERN_READOUT/LVDS_TEST_PATTERN_READOUT.srcs/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0.xci
# IP: The module: 'TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_TEST_PATTERN_READOUT/LVDS_TEST_PATTERN_READOUT.gen/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_TEST_PATTERN_READOUT/LVDS_TEST_PATTERN_READOUT.gen/sources_1/bd/TEST_PATTERN_TO_AXIS/ip/TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_PATTERN_TO_AXIS_LVDS_to_AXIS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
