# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/signal_generator_LVDS_to_AXIS_0_0.xci
# IP: The module: 'signal_generator_LVDS_to_AXIS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/LVDS_to_AXIS_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/LVDS_to_AXIS_ila_0_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_LVDS_to_AXIS_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/signal_generator_LVDS_to_AXIS_0_0.xci
# IP: The module: 'signal_generator_LVDS_to_AXIS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4} -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/LVDS_to_AXIS_ila_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ila_0_0/LVDS_to_AXIS_ila_0_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_LVDS_to_AXIS_0_0/src/LVDS_to_AXIS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_LVDS_to_AXIS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
