# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/histo/histo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo || ORIG_REF_NAME==histo} -quiet] -quiet

# IP: bd/histo/ip/histo_axis_data_fifo_0_0/histo_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_axis_data_fifo_0_0 || ORIG_REF_NAME==histo_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_in_line_and_in_frame_0/histo_in_line_and_in_frame_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_in_line_and_in_frame_0 || ORIG_REF_NAME==histo_in_line_and_in_frame_0} -quiet] -quiet

# IP: bd/histo/ip/histo_util_vector_logic_0_0/histo_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_util_vector_logic_0_0 || ORIG_REF_NAME==histo_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_util_vector_logic_1_1/histo_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_util_vector_logic_1_1 || ORIG_REF_NAME==histo_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/histo/ip/histo_HISTOGRAM_ARBITER_FSM_0_0/histo_HISTOGRAM_ARBITER_FSM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_HISTOGRAM_ARBITER_FSM_0_0 || ORIG_REF_NAME==histo_HISTOGRAM_ARBITER_FSM_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_sorter_0_0/histo_sorter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_sorter_0_0 || ORIG_REF_NAME==histo_sorter_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_negedge_detect_0_0/histo_negedge_detect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_negedge_detect_0_0 || ORIG_REF_NAME==histo_negedge_detect_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_xlconstant_0_0/histo_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_xlconstant_0_0 || ORIG_REF_NAME==histo_xlconstant_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_posedge_detect_0_0/histo_posedge_detect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_posedge_detect_0_0 || ORIG_REF_NAME==histo_posedge_detect_0_0} -quiet] -quiet

# IP: bd/histo/ip/histo_ila_sorter_0/histo_ila_sorter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==histo_ila_sorter_0 || ORIG_REF_NAME==histo_ila_sorter_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/hist_stream/hist_stream.gen/sources_1/bd/histo/histo_ooc.xdc
