# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/zync_proj/main_constraints.xdc

# Block Designs: bd/hw_proj1/hw_proj1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1 || ORIG_REF_NAME==hw_proj1} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_processing_system7_0_0/hw_proj1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_processing_system7_0_0 || ORIG_REF_NAME==hw_proj1_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_axi_gpio_0_0/hw_proj1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_axi_gpio_0_0 || ORIG_REF_NAME==hw_proj1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_axi_smc_0/hw_proj1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_axi_smc_0 || ORIG_REF_NAME==hw_proj1_axi_smc_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_rst_ps7_0_50M_0/hw_proj1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_proj1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_axi_quad_spi_0_0 || ORIG_REF_NAME==hw_proj1_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_xlconcat_0_0/hw_proj1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_xlconcat_0_0 || ORIG_REF_NAME==hw_proj1_xlconcat_0_0} -quiet] -quiet

# XDC: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/hw_proj1_ooc.xdc
