# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/LVDS_to_AXIS/LVDS_to_AXIS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS || ORIG_REF_NAME==LVDS_to_AXIS} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_lvds_master_0_0/LVDS_to_AXIS_lvds_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_lvds_master_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_lvds_master_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_lvds_output_0_0/LVDS_to_AXIS_lvds_output_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_lvds_output_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_lvds_output_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_lvds_input_0_0/LVDS_to_AXIS_lvds_input_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_lvds_input_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_lvds_input_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_l_clk_in_0/LVDS_to_AXIS_l_clk_in_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_l_clk_in_0 || ORIG_REF_NAME==LVDS_to_AXIS_l_clk_in_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_sdo_0/LVDS_to_AXIS_sdo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_sdo_0 || ORIG_REF_NAME==LVDS_to_AXIS_sdo_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_ila_0_0/LVDS_to_AXIS_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_clk_wiz_0_0/LVDS_to_AXIS_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_clk_wiz_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_clk_wiz_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_ila_1_0/LVDS_to_AXIS_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_ila_1_0 || ORIG_REF_NAME==LVDS_to_AXIS_ila_1_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_to_axis_production/LVDS_to_axis_production.gen/sources_1/bd/LVDS_to_AXIS/LVDS_to_AXIS_ooc.xdc
