# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/emulator_4x8bit/emulator_4x8bit.srcs/sources_1/bd/laser/ip/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0.xci
# IP: The module: 'laser_bram_ctrl_laser_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/emulator_4x8bit/emulator_4x8bit.gen/sources_1/bd/laser/ip/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'laser_bram_ctrl_laser_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/emulator_4x8bit/emulator_4x8bit.srcs/sources_1/bd/laser/ip/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0.xci
# IP: The module: 'laser_bram_ctrl_laser_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/emulator_4x8bit/emulator_4x8bit.gen/sources_1/bd/laser/ip/laser_bram_ctrl_laser_0/laser_bram_ctrl_laser_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'laser_bram_ctrl_laser_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
