`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 23.09.2025 09:24:59
// Design Name: 
// Module Name: IDDR
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 

//          this is a successful attempt to create a DDR LVDS module that consists of two always_ff - blocks
//          two always-ff blocks is inherently messy, which is why this module is such a mess.
//          it has been patched until it worked, but has not really been designed with a state machine in mind
//          alternatives to this approach would have been:

//          have a clock twice as fast as the LVDS clck, which can then trigger logic on the posedge only
//          this has the downside that it requires a very fast clock on the fpga: 500 Mhz for 250 MHz of LVDS clock rate.
//          i am pretty sure that the zedboards FPGA can not provide such a high clock rate, which is why I needed to design a logic that works on both edges of the clock
//          verilog doesnt allow something like: always_ff(@posedge clock OR negedge clock). so one has to have to always_ff blocks, one for posedge clock, one for negedge clock.
//          each always_ff block just registers the D signal at its edge of the C signal. in the end the two received data "halves" have to be zipped together with the right always_ff starting

//          Another way of doing it might have been: 
//          using IDDR blocks: these would take in the two data bits per C cycle and present them to the FPGA logic at the same time synchronously to one clock edge.
//          sady, i have only now understood this,  way after I made the "two alyways_ff blocks" method work

//          
//          this module works as follows:
//          each always-block checks wether it is the first to notice that a new frame of data is arriving.
//          they also shift their shift registers in and sample the data line if a frame of data is coming in
//          
//          in the end, bot these shift registers are "zipped" and the resulting long message is sent via the axi stream protocol.

//          currently there is no procedure in place for checking if tready is low.
//          if the axis FIFO is full we will simply miss this message, which is not a big deal. a warning will be generated by the fifo
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module DDR_fabric_even_simpler
    #(parameter NUM_TRANSACTIONS = 256,  // after how many transactions does the tlast signal assert?
      parameter CLOCKRATIO = 2)  //how many times faster is the lvds clock than the axi stream clock? tested with values 2 and four
    (
    input wire [5:0] msglen, //sum of gpx2's stop_data_bitwidth and refindex_bitwidth
    input wire aresetn,
    input wire C, // LVDS clock
    input wire D, //LVDS data. this is actually a delayed signal. an IDELAYE2 instance delays the signal with a programmable amount wrt the C signal
    input wire F,  //LVDS frame. the frame signals the start of an LVDS message. this is actually a delayed signal. an IDELAYE2 instance delays the signal with a programmable amount wrt the C signal
    
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TREADY" *)
    (* X_INTERFACE_PARAMETER = "FREQ_HZ 100000000" *)
    input wire tready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TDATA" *)
    output wire [63:0] tdata_delayed,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TVALID" *)
    output wire tvalid_delayed,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TLAST" *)
    output wire tlast_delayed
    );

localparam TRANSACTION_COUNTER_WIDTH = $clog2(NUM_TRANSACTIONS);
localparam TDATA_WIDTH = 64;
localparam COUNTER_WIDTH = $clog2(TDATA_WIDTH);

reg tvalid;
reg tlast;
reg [63:0] tdata;
reg neg_tvalid;
reg pos_tlast;
reg neg_tlast;    
reg [31:0] posedge_Qs;  //temporary, unstable shift registers for clocking in the data at half the DDR clock
reg [31:0] negedge_Qs;
reg [TRANSACTION_COUNTER_WIDTH-1:0] transaction_counter;  //for the tlast signal
reg posedge_first;
reg negedge_first;
reg [COUNTER_WIDTH-1:0] bit_counter;  //for counting to message_length in one photon event: x bits for refindex and y bits for stop result
wire [63:0] tdata_posedge_first;
wire [63:0] tdata_negedge_first;
reg [63:0] tdata_posedge_first_synchronised;
reg [63:0] tdata_negedge_first_synchronised;
reg F_synchronised_posedge;
reg F_synchronised_posedge_delayed;
reg D_synchronised_posedge;
reg F_synchronised_negedge;
reg F_synchronised_negedge_delayed;
reg D_synchronised_negedge;
reg prepare_tvalid_posedge_first;
reg prepare_tvalid_negedge_first;
reg F_synchronised_negedge_synchronised;
reg [63:0] tdata_negedge_first_synchronised_synchronised;
reg counter_enabled;
wire [63:0] tdata_mask;


// the first always_ff block
always @(posedge C, negedge aresetn) begin
        if (!aresetn) begin
            posedge_Qs <= 32'b0;
            tdata <= 0;
            tvalid <= 1'b0;
            tlast <= 1'b0;
            transaction_counter <= NUM_TRANSACTIONS-1;
            posedge_first <= 0;
            negedge_first <= 0;
            bit_counter <= 0;  
            F_synchronised_posedge <= 0;
            D_synchronised_posedge <= 0;
            tdata_posedge_first_synchronised <= 0;
            prepare_tvalid_posedge_first <= 0;
            prepare_tvalid_negedge_first <= 0;
            counter_enabled <= 0;
            F_synchronised_negedge_synchronised <=0 ;
            tdata_negedge_first_synchronised_synchronised <= 0;
        end
        else begin           
            posedge_Qs <= {posedge_Qs[30:0], D_synchronised_posedge};  //shift data into shift reg
            if(counter_enabled) begin
                bit_counter <= bit_counter-1;
                end
            F_synchronised_posedge <= F;
            F_synchronised_posedge_delayed <= F_synchronised_posedge;
            D_synchronised_posedge <= D;
            tdata_posedge_first_synchronised <= tdata_posedge_first;
            F_synchronised_negedge_synchronised <= F_synchronised_negedge;
            tdata_negedge_first_synchronised_synchronised <= tdata_negedge_first_synchronised;
            //determine posedge_first/negedge_first:
            if((F_synchronised_posedge&!F_synchronised_negedge_synchronised)&F)begin  //if we notice a posedge of F and the negedge_always_ff has not detected it first
                counter_enabled <= 1;
                posedge_first <= 1;
                negedge_first <= 0;
                bit_counter <= msglen/2-1;
                end
            if(((!F_synchronised_posedge_delayed)&F_synchronised_negedge_synchronised)&F)begin  //if the negedge always_ff block has detected a posedge of F first
                counter_enabled <= 1;
                negedge_first <= 1;
                posedge_first <= 0;
                bit_counter <= msglen/2-1;
                end
             
             if(!bit_counter & posedge_first)begin
                prepare_tvalid_posedge_first <= 1;
                end
             if(prepare_tvalid_posedge_first) begin
                prepare_tvalid_posedge_first <= 0;
                tvalid <= 1;
                tdata <= tdata_posedge_first_synchronised&tdata_mask;
                transaction_counter <= transaction_counter -1;
                if ((!transaction_counter)) begin
                        tlast <= 1'b1;
                        transaction_counter <= NUM_TRANSACTIONS-1;
                        end
                        
                if (!F_synchronised_posedge_delayed) begin
                    counter_enabled <= 0;
                    end                        
                        
                        
                end

                
             if(!bit_counter & negedge_first)begin
                prepare_tvalid_negedge_first <= 1;
                end
             if(prepare_tvalid_negedge_first) begin
                prepare_tvalid_negedge_first<= 0;
                tvalid <= 1;
                tdata <= tdata_negedge_first_synchronised_synchronised&tdata_mask;

                transaction_counter <= transaction_counter-1;
                if ((!transaction_counter)) begin
                        tlast <= 1'b1;
                        transaction_counter <= NUM_TRANSACTIONS-1;
                        end
                if (!F_synchronised_negedge_synchronised) begin
                    counter_enabled <= 0;
                    end                                
                end  
                
      
                

                
                
             //ensure tvalid and tlast are high for one clock cycle only. this assumes no backpressure on the axi stream bus.
             //but thats okay since we have no way of dealing with backpressure anyways so we just have to throw an error when the LVDS messages cannot be handled
             if (tvalid)begin
                tvalid <= 0;
                tlast <= 0;
             end
        end             
end

// the second always_ff block: it only shifts data into a shift register, all the bookkeeping work is done by the first always_ff block
always @(negedge C, negedge aresetn) begin
        if (!aresetn) begin
            negedge_Qs <= 32'b0;
            tdata_negedge_first_synchronised <= 0;
            F_synchronised_negedge <= 0;
            F_synchronised_negedge_delayed <= 0;
            D_synchronised_negedge <= 0;  //might still be metastable if D changes too late. but we use idelay to prevent this from happening
        end
        else begin
            F_synchronised_negedge <= F;
            F_synchronised_negedge_delayed <= F_synchronised_negedge;
            D_synchronised_negedge <= D;
            negedge_Qs <= {negedge_Qs[30:0], D_synchronised_negedge};  //shift data into shift reg
            tdata_negedge_first_synchronised <= tdata_negedge_first;
            end
    end


// Zip the words when the first data bit was on a posedge of the clock
zip_words zipper_posedge_first (
    .word1(posedge_Qs),
    .word2(negedge_Qs),
    .result(tdata_posedge_first)
);

// Zip the words when the first data bit was on a negedge of the clock
zip_words zipper_negedge_first (
    .word1(negedge_Qs),
    .word2(posedge_Qs),
    .result(tdata_negedge_first)
);

// without this delay, the AXI stream fifo is not ready to accept the axi stream data yet
delay_by_X_clocks delay_tvalid (
    .data_in(tvalid),
    .data_out(tvalid_delayed),
    .clk(C),
    .aresetn(aresetn)
);             

delay_by_X_clocks delay_tlast (
    .data_in(tlast),
    .data_out(tlast_delayed),
    .clk(C),
    .aresetn(aresetn)
);    

delay_64bit_by_X_clocks delay_tdata (
    .data_in(tdata),
    .data_out(tdata_delayed),
    .clk(C),
    .aresetn(aresetn)
);   


// a helper function to generate a mask, eg generates 0x00000007 for X = 3
function [64-1:0] gen_mask(input [64-1:0] X);
    gen_mask = (1 << X) - 1;
endfunction

assign tdata_mask = gen_mask(msglen);
 

endmodule
              
//zip the words with msb of word1 becoming the msb of the result
module zip_words (
    input wire [31:0] word1,  // First 32-bit word
    input wire [31:0] word2,  // Second 32-bit word
    output reg [63:0] result  // Resulting 64-bit word
);
    integer i;
    always @(*) begin
        for (i = 0; i < 32; i = i + 1) begin
            result[2*i]   = word2[i];  // Even bits: word2
            result[2*i+1] = word1[i];  // Odd bits: word1
        end
    end
    
    

    
    
endmodule




// delay axi stream, so that fifo can assert tready before tvalid arrives:

module delay_64bit_by_X_clocks (
    input wire clk,          // Clock signal
    input wire aresetn,        // Active-high reset
    input wire [63:0] data_in,  // 64-bit input signal
    output reg [63:0] data_out  // 64-bit output signal (delayed by 60 cycles)
);

// Parameter for the number of delay cycles
parameter DELAY_CYCLES = 60;       // Default delay is 60 cycles

// X-stage shift register for 64-bit data
reg [63:0] shift_reg [DELAY_CYCLES-1:0];  // Array of 60 64-bit registers

integer i;
always @(posedge clk or negedge aresetn) begin
    if (!aresetn) begin
        // Asynchronously clear all stages
        for (i = 0; i < DELAY_CYCLES; i = i + 1) begin
            shift_reg[i] <= 64'b0;
        end
        data_out <= 64'b0;
    end else begin
        // Shift the data through the register
        shift_reg[DELAY_CYCLES-1] <= data_in;  // New data goes into the last stage
        for (i = DELAY_CYCLES-2; i >= 0; i = i - 1) begin
            shift_reg[i] <= shift_reg[i + 1];  // Shift data to the next stage
        end
        data_out <= shift_reg[0];  // Output the oldest value
    end
end

endmodule


module delay_by_X_clocks (
    input wire clk,        // Clock signal
    input wire aresetn,      // Active-high reset
    input wire data_in,    // Input signal to be delayed
    output reg data_out    // Output signal (delayed by 60 cycles)
);
// Parameter for the number of delay cycles
parameter DELAY_CYCLES = 60;       // Default delay is 60 cycles
// Shift register to delay the signal by 60 cycles
reg [DELAY_CYCLES-1:0] shift_reg;     // 60-stage shift register

always @(posedge clk or negedge aresetn) begin
    if (!aresetn) begin
        // Asynchronous reset: clear all stages
        shift_reg <= 0;
        data_out <= 1'b0;
    end else begin
        // Shift the data through the register
        shift_reg <= {data_in, shift_reg[DELAY_CYCLES-1:1]};
        data_out <= shift_reg[0];  // Output the oldest value
    end
end

endmodule