# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.srcs/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/hw_proj1_axi_smc_0.xci
# IP: The module: 'hw_proj1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/bd_9633.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_0/bd_9633_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_1/bd_9633_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_2/bd_9633_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_3/bd_9633_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_4/bd_9633_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_5/bd_9633_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_6/bd_9633_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_7/bd_9633_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_8/bd_9633_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_9/bd_9633_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_10/bd_9633_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_11/bd_9633_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_12/bd_9633_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_13/bd_9633_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_14/bd_9633_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_15/bd_9633_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_16/bd_9633_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_17/bd_9633_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_18/bd_9633_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_19/bd_9633_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_20/bd_9633_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_21/bd_9633_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_22/bd_9633_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_23/bd_9633_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_24/bd_9633_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_25/bd_9633_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_26/bd_9633_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_27/bd_9633_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_28/bd_9633_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_29/bd_9633_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_30/bd_9633_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_31/bd_9633_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_32/bd_9633_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_33/bd_9633_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_34/bd_9633_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_35/bd_9633_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_36/bd_9633_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_37/bd_9633_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_38/bd_9633_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_39/bd_9633_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_1/bd_9633_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_1/bd_9633_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_2/bd_9633_arinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_3/bd_9633_rinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_4/bd_9633_awinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_5/bd_9633_winsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_6/bd_9633_binsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_7/bd_9633_aroutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_8/bd_9633_routsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_9/bd_9633_awoutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_10/bd_9633_woutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_11/bd_9633_boutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_12/bd_9633_arni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_13/bd_9633_rni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_14/bd_9633_awni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_15/bd_9633_wni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_16/bd_9633_bni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_20/bd_9633_s00a2s_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_21/bd_9633_sarn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_22/bd_9633_srn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_23/bd_9633_sawn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_24/bd_9633_swn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_25/bd_9633_sbn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_26/bd_9633_m00s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_27/bd_9633_m00arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_28/bd_9633_m00rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_29/bd_9633_m00awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_30/bd_9633_m00wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_31/bd_9633_m00bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_33/bd_9633_m01s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_34/bd_9633_m01arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_35/bd_9633_m01rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_36/bd_9633_m01awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_37/bd_9633_m01wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_38/bd_9633_m01bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.srcs/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/hw_proj1_axi_smc_0.xci
# IP: The module: 'hw_proj1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/bd_9633.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_0/bd_9633_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_1/bd_9633_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_2/bd_9633_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_3/bd_9633_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_4/bd_9633_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_5/bd_9633_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_6/bd_9633_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_7/bd_9633_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_8/bd_9633_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_9/bd_9633_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_10/bd_9633_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_11/bd_9633_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_12/bd_9633_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_13/bd_9633_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_14/bd_9633_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_15/bd_9633_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_16/bd_9633_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_17/bd_9633_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_18/bd_9633_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_19/bd_9633_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_20/bd_9633_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_21/bd_9633_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_22/bd_9633_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_23/bd_9633_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_24/bd_9633_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_25/bd_9633_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_26/bd_9633_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_27/bd_9633_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_28/bd_9633_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_29/bd_9633_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_30/bd_9633_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_31/bd_9633_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_32/bd_9633_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_33/bd_9633_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_34/bd_9633_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_35/bd_9633_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_36/bd_9633_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_37/bd_9633_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_38/bd_9633_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_39/bd_9633_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_1/bd_9633_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_1/bd_9633_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_2/bd_9633_arinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_3/bd_9633_rinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_4/bd_9633_awinsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_5/bd_9633_winsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_6/bd_9633_binsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_7/bd_9633_aroutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_8/bd_9633_routsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_9/bd_9633_awoutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_10/bd_9633_woutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_11/bd_9633_boutsw_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_12/bd_9633_arni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_13/bd_9633_rni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_14/bd_9633_awni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_15/bd_9633_wni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_16/bd_9633_bni_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_20/bd_9633_s00a2s_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_21/bd_9633_sarn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_22/bd_9633_srn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_23/bd_9633_sawn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_24/bd_9633_swn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_25/bd_9633_sbn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_26/bd_9633_m00s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_27/bd_9633_m00arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_28/bd_9633_m00rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_29/bd_9633_m00awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_30/bd_9633_m00wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_31/bd_9633_m00bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_33/bd_9633_m01s2a_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_34/bd_9633_m01arn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_35/bd_9633_m01rn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_36/bd_9633_m01awn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_37/bd_9633_m01wn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/bd_0/ip/ip_38/bd_9633_m01bn_0_ooc.xdc

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
