# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_sandbox/LVDS_sandbox.srcs/sources_1/bd/led/ip/led_c_counter_binary_0_0/led_c_counter_binary_0_0.xci
# IP: The module: 'led_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_sandbox/LVDS_sandbox.gen/sources_1/bd/led/ip/led_c_counter_binary_0_0/led_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_sandbox/LVDS_sandbox.srcs/sources_1/bd/led/ip/led_c_counter_binary_0_0/led_c_counter_binary_0_0.xci
# IP: The module: 'led_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/LVDS_sandbox/LVDS_sandbox.gen/sources_1/bd/led/ip/led_c_counter_binary_0_0/led_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
