# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.srcs/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0.xci
# IP: The module: 'hw_proj1_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.srcs/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0.xci
# IP: The module: 'hw_proj1_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Desktop/zync_proj/2024.2/zybo_z7_20/zybo_gpx2/zybo_gpx2/zybo_gpx2.gen/sources_1/bd/hw_proj1/ip/hw_proj1_axi_quad_spi_0_0/hw_proj1_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
