# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/LVDS_to_AXIS/LVDS_to_AXIS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS || ORIG_REF_NAME==LVDS_to_AXIS} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_axis_data_fifo_0_0/LVDS_to_AXIS_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_lvds_output_0_0/LVDS_to_AXIS_lvds_output_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_lvds_output_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_lvds_output_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_1/LVDS_to_AXIS_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_1_0/LVDS_to_AXIS_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_idelay_ctrl_0_0/LVDS_to_AXIS_util_idelay_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_idelay_ctrl_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_idelay_ctrl_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_vector_logic_0_0/LVDS_to_AXIS_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_vector_logic_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_1_1/LVDS_to_AXIS_util_ds_buf_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_1_1} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_util_ds_buf_0_4/LVDS_to_AXIS_util_ds_buf_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4 || ORIG_REF_NAME==LVDS_to_AXIS_util_ds_buf_0_4} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_IDELAY_DATA_0_0/LVDS_to_AXIS_IDELAY_DATA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_IDELAY_DATA_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_IDELAY_DATA_0_0} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_IDELAY_DATA_0_1/LVDS_to_AXIS_IDELAY_DATA_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_IDELAY_DATA_0_1 || ORIG_REF_NAME==LVDS_to_AXIS_IDELAY_DATA_0_1} -quiet] -quiet

# IP: bd/LVDS_to_AXIS/ip/LVDS_to_AXIS_DDR_fabric_even_simp_0_0/LVDS_to_AXIS_DDR_fabric_even_simp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==LVDS_to_AXIS_DDR_fabric_even_simp_0_0 || ORIG_REF_NAME==LVDS_to_AXIS_DDR_fabric_even_simp_0_0} -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/LVDS/DDR_LVDS_FABRIC/DDR_LVDS_FABRIC.gen/sources_1/bd/LVDS_to_AXIS/LVDS_to_AXIS_ooc.xdc
