# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0.xci
# IP: The module: 'signal_generator_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.srcs/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0.xci
# IP: The module: 'signal_generator_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marce/OneDrive/Dokumente/zynq_project/photonsorting/sg_stream/sg_stream.gen/sources_1/bd/signal_generator/ip/signal_generator_axi_gpio_1_0/signal_generator_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'signal_generator_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
