@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 02 15:40:14 +0100 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim block_design_elaboreate_tb_behav -key {Behavioral:block_design_elaborate_new:Functional:block_design_elaboreate_tb} -tclbatch block_design_elaboreate_tb.tcl -protoinst "protoinst_files/histo.protoinst" -log simulate.log"
call xsim  block_design_elaboreate_tb_behav -key {Behavioral:block_design_elaborate_new:Functional:block_design_elaboreate_tb} -tclbatch block_design_elaboreate_tb.tcl -protoinst "protoinst_files/histo.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
